spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8302/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0 
      enableSelfPreservation: false
      maxThreadsForPeerReplication: 0
      
zuul:
  #service will be mapped under /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
    